const data=window.portfolio;
const main=document.querySelector('main');
document.querySelector('.skip').addEventListener('click',event=>{event.preventDefault();main.focus();main.scrollIntoView();});
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function imageSlot(src,label,cls=''){return src?`<figure class="visual ${cls}"><img src="${esc(src)}" alt="${esc(label)}" loading="lazy"></figure>`:`<div class="visual placeholder ${cls}" role="img" aria-label="待添加：${esc(label)}"><span class="slot-corner">IMAGE TO COME</span><div class="slot-label"><span class="slot-line"></span><span>${esc(label)}</span><small>作品图片待添加</small></div></div>`;}
function projectLink(p,i){return `<article class="project project-${i+1}"><a href="#/project/${p.slug}" aria-label="查看${esc(p.title)}项目详情">${imageSlot(p.cover,`${p.title} · 封面主视觉`)}<div class="caption"><div><span class="index">0${i+1}</span><h3>${homeHeading(p.homeTitle||p.title)}</h3></div><span class="meta">${esc(p.category)}<span class="arrow">↗</span></span></div></a></article>`;}
function home(){return `<section class="intro cloud-intro" aria-label="创作领域词云"><h1 class="sr-only">未匀斋作品选</h1><div class="word-cloud">${wordCloud()}</div></section><section aria-labelledby="works-title"><div class="section-heading"><h2 id="works-title">设计作品选 <span>Selected design</span></h2><span class="muted">01—05</span></div><div class="projects balanced-projects">${data.projects.map(projectLink).join('')}</div></section><section class="fine-art-home" aria-labelledby="fine-art-title"><a href="#/fine-art"><div><p class="eyebrow">FINE ART / 美术</p><h2 id="fine-art-title">美术作品选</h2></div><span class="text-link">进入作品选 <span aria-hidden="true">→</span></span></a></section><aside class="closing"><p>诗家清景在新春，<br>绿柳才黄半未匀。</p><a class="text-link" href="#/about">关于我 <span>About →</span></a></aside>`;}
function fineArt(){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>FINE ART</span></div><section class="simple-page"><p class="eyebrow">SELECTED ARTWORKS / 美术作品选</p><h1>美术作品选</h1><ol class="directory-list fine-art-directory">${data.fineArt.map((s,i)=>`<li><a href="#/fine-art/${s.id}"><span class="directory-number">0${i+1}</span><span>${esc(s.title)}</span><span class="directory-size"></span><span>↗</span></a></li>`).join('')}</ol></section>`;}
function fineArtPage(s){const items=[...s.assets];if(s.id==='pen')for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}return `<div class="detail-top"><a class="text-link" href="#/fine-art">← 美术作品选目录</a><span>FINE ART</span></div><section class="item-intro"><h1>${esc(s.title)}</h1></section>${items.length?'<section class="pen-gallery '+(s.id==='digital'?'digital-gallery':'')+'">'+items.map(a=>'<div class="pen-piece" style="--piece-width:'+(85+Math.floor(Math.random()*16))+'%;--piece-offset:'+Math.floor(Math.random()*5)+'rem">'+fineArtFigure(a)+'</div>').join('')+'</section>':'<p class="venue-pending">作品陆续整理中。</p>'}`;}
function detail(p){if(p.presentation==='salon')return salonEssay(p);if(p.presentation==='jinhuidui')return jinhuiduiEssay(p);if(p.presentation==='essay')return peonyEssay(p);if(p.pages)return otherDirectory(p);if(p.sections)return galleryDetail(p);const i=data.projects.indexOf(p),next=data.projects[(i+1)%5];return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>${p.en} / 05</span></div><section class="project-intro"><p class="eyebrow">SELECTED WORK / 0${i+1}</p><h1>${esc(p.title)}</h1><div class="project-summary"><p class="description">${esc(p.description)||'项目介绍待补充。这里将呈现项目背景、设计命题与核心概念。'}</p><dl><div><dt>年份 / Year</dt><dd>${esc(p.year)||'待补充'}</dd></div><div><dt>类别 / Category</dt><dd>${esc(p.category)}</dd></div><div><dt>职责 / Role</dt><dd>${esc(p.role)||'待补充'}</dd></div></dl></div></section>${imageSlot(p.cover,`${p.title} · 完整主视觉`,'hero-image')}<section class="story"><div class="story-heading"><span>01 / CONCEPT</span><h2>概念与推演</h2><p>待补充设计思路、原始草图与概念演变。</p></div>${imageSlot(p.images[0],'原始草图 / 概念推演')}</section><section class="story"><div class="story-heading"><span>02 / SYSTEM</span><h2>视觉系统</h2><p>待补充字体、色彩、图形与版式设计。</p></div><div class="image-pair">${imageSlot(p.images[1],'字体与色彩')}${imageSlot(p.images[2],'图形与版式')}</div></section><section class="story"><div class="story-heading"><span>03 / APPLICATION</span><h2>最终呈现</h2><p>待补充作品实拍与应用效果。</p></div>${imageSlot(p.images[3],'最终应用 / 实物摄影')}</section><a class="next-project" href="#/project/${next.slug}"><span>下一个项目 <small>NEXT PROJECT</small></span><strong>${esc(next.title)}</strong><span>→</span></a>`;}
function about(){return `<section class="simple-page"><p class="eyebrow">ABOUT / 关于</p><h1>以观察为起点，<br><span>以设计回应。</span></h1><div class="about-grid">${imageSlot('','个人肖像 / 工作场景','portrait')}<div class="about-copy"><h2>${esc(data.name)||'设计师姓名待补充'}</h2><p>${esc(data.bio)||'个人简介待补充。这里将介绍你的设计方向、关注的问题，以及你如何理解和实践视觉设计。'}</p><div class="about-row"><span>设计方向</span><p>视觉设计<br><span class="muted">具体方向待补充</span></p></div><div class="about-row"><span>经历</span><p class="muted">教育与工作经历待补充</p></div><a href="#/contact" class="text-link">联系我 <span>Contact →</span></a></div></div></section>`;}
function contact(){return `<section class="simple-page contact-page"><p class="eyebrow">CONTACT / 联系</p><h1>从一次对话，<br><span>开始。</span></h1><div class="contact-content"><p>项目合作、工作机会，<br>或关于设计的交流。</p><div class="contact-details"><dl><div><dt>【邮箱】</dt><dd><a href="mailto:${esc(data.email)}">${esc(data.email)}</a></dd></div><div><dt>【微信】</dt><dd>${esc(data.wechat)}</dd></div><div><dt>【电话】</dt><dd><a href="tel:${esc(data.phone)}">${esc(data.phone)}</a></dd></div><div><dt>【公众号】</dt><dd>${esc(data.publicAccount)}</dd></div></dl></div></div><a href="#/" class="text-link">浏览作品 <span>Work →</span></a></section>`;}
function render(){const route=location.hash.slice(1)||'/';let html,active='work',title='作品';if(route==='/'){html=home()}else if(route.startsWith('/fine-art/')){const s=data.fineArt.find(s=>route==='/fine-art/'+s.id);html=s?fineArtPage(s):fineArt();title=s?s.title:'美术作品选'}else if(route==='/fine-art'){html=fineArt();title='美术作品选'}else if(route==='/about'){html=about();active='about';title='关于'}else if(route==='/contact'){html=contact();active='contact';title='联系'}else if(/^\/project\/(begonia|peony|project-four|project-five)\/[^/]+$/.test(route)){const parts=route.split('/'),p=data.projects.find(p=>p.slug===parts[2]),page=p?.pages?.find(s=>s.id===parts[3]);html=page?otherPage(p,page):'<section class="simple-page"><h1>未找到页面</h1><a href="#/">返回首页</a></section>';title=page? p.title+' · '+page.title:'未找到页面'}else if(route.startsWith('/project/reading/')){const p=data.projects[0],id=route.split('/')[3],s=p.sections.find(s=>s.number===id);html=id==='realization'?realizationPage(p):id==='venue'?venuePage(p):s?artPage(p,s):'<section class="simple-page"><h1>未找到页面</h1><a href="#/project/reading">返回项目目录</a></section>';title=id==='realization'?'成品落地':s?s.title:'会场视觉'}else{const p=data.projects.find(p=>route===`/project/${p.slug}`);if(p){html=detail(p);title=p.title}else{html='<section class="simple-page"><h1>未找到页面</h1><a class="text-link" href="#/">返回作品首页 →</a></section>'}}
main.innerHTML=html;document.title=`${title} — 视觉设计作品集`;document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});window.scrollTo(0,0);if(location.hash)main.focus({preventScroll:true});document.getElementById('copy-email')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(data.email);document.getElementById('copy-status').textContent='邮箱已复制'}catch{document.getElementById('copy-status').textContent='请选中上方邮箱手动复制'}});}
window.addEventListener('hashchange',render);render();

function projectHeading(p){return `<h1 class="reading-title">浙江大学文学院第十六届<br>冬至·中国传统艺术赏读会<span>——活动视觉策划与系统设计</span></h1>`;}
function galleryDetail(p){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>PROJECT 01 / 05</span></div><section class="project-intro"><p class="eyebrow">PROJECT OVERVIEW / 项目总览</p>${projectHeading(p)}</section><div class="reading-overview"><aside class="project-facts"><dl>${[['委托方',[p.client]],['周期',[p.period]],['职责',p.responsibilities],['协作',p.collaborators]].map(([k,v])=>`<div><dt>【${k}】</dt><dd>${v.map(esc).join('<br>')}</dd></div>`).join('')}</dl></aside><section class="project-directory" aria-labelledby="directory-title"><p class="eyebrow">【成果】</p><h2 id="directory-title">宣传品 <small class="muted">/ 8 类</small></h2><ol class="directory-list">${p.sections.map(s=>`<li><a href="#/project/reading/${s.number}"><span class="directory-number">${s.number}</span><span>${esc(s.title)}</span><span class="directory-size">${esc(s.size)}</span><span aria-hidden="true">↗</span></a></li>`).join('')}</ol><a class="venue-entry" href="#/project/reading/venue"><h2>会场视觉 <small class="muted">/ 3 类</small></h2><span aria-hidden="true">↗</span></a><a class="venue-entry" href="#/project/reading/realization"><h2>成品落地 <small class="muted">/ 7 张</small></h2><span aria-hidden="true">↗</span></a></section></div>`;}
function artPage(p,s){const index=p.sections.indexOf(s),next=p.sections[index+1];return `<div class="detail-top"><a class="text-link" href="#/project/reading">← 项目目录</a><span>赏读会 / ${s.number}</span></div><section class="item-intro"><p class="eyebrow">活动视觉策划与系统设计 / 宣传品</p><h1>${esc(s.title)}</h1><p class="item-spec">${esc(s.size)}${s.assets.length>1?' · '+s.assets.length+' 张':''}</p></section><section class="art-section art-${s.layout}"><div class="art-grid">${s.assets.map((a,i)=>`<figure class="artwork"><a href="${esc(a.src)}" target="_blank" rel="noopener" aria-label="查看大图：${esc(a.label)}"><img src="${esc(a.src)}" width="${a.width}" height="${a.height}" alt="赏读会 · ${esc(a.label)}" loading="${i===0?'eager':'lazy'}" decoding="async"></a><figcaption>${esc(a.label)}<a href="${esc(a.src)}" target="_blank" rel="noopener">查看大图 ↗</a></figcaption></figure>`).join('')}</div></section><nav class="item-pagination" aria-label="宣传品导航"><a href="#/project/reading">返回目录</a>${index>0?`<a href="#/project/reading/${p.sections[index-1].number}">← ${esc(p.sections[index-1].title)}</a>`:''}${next?`<a href="#/project/reading/${next.number}">${esc(next.title)} →</a>`:'<a href="#/project/reading/venue">会场视觉 →</a>'}</nav>`;}
function venuePage(p){return `<div class="detail-top"><a class="text-link" href="#/project/reading">← 项目目录</a><span>赏读会 / 会场视觉</span></div><section class="item-intro"><p class="eyebrow">VENUE VISUALS</p><h1>会场视觉</h1></section><section class="art-section art-wide"><div class="art-grid">${p.venueAssets.map(essayFigure).join('')}</div></section><nav class="item-pagination" aria-label="会场视觉导航"><a href="#/project/reading">返回项目目录</a></nav>`;}

function otherDirectory(p){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>${esc(p.en)} / 05</span></div><section class="project-intro"><p class="eyebrow">PROJECT OVERVIEW / 项目总览</p><h1 class="reading-title">${esc(p.fullTitle||p.title)}${p.subtitle?`<span>${esc(p.subtitle)}</span>`:''}</h1></section><div class="reading-overview"><aside class="project-facts"><dl>${[['委托方',p.client],['周期',p.period],['职责',p.role],['协作',p.collaborators?.join('、')]].filter(([k])=>!p.hideRoleAndCollaboration||!['职责','协作'].includes(k)).map(([k,v])=>`<div><dt>【${k}】</dt><dd>${esc(v)||'待补充'}</dd></div>`).join('')}</dl></aside><section class="project-directory" aria-labelledby="directory-title"><p class="eyebrow">【项目目录】</p><h2 id="directory-title">作品内容 <small class="muted">/ ${p.pages.length} 部分</small></h2><ol class="directory-list">${p.pages.map((s,i)=>`<li><a href="#/project/${p.slug}/${s.id}"><span class="directory-number">0${i+1}</span><span>${esc(s.title)}</span><span class="directory-size">${s.assets.length?s.assets.length+' 张':'待补充'}</span><span>↗</span></a></li>`).join('')}</ol></section></div>`;}

function otherPage(p,s){const i=p.pages.indexOf(s),next=p.pages[i+1];return `<div class="detail-top"><a class="text-link" href="#/project/${p.slug}">← 项目目录</a><span>${esc(p.title)} / 0${i+1}</span></div><section class="item-intro"><p class="eyebrow">${esc(p.title)}</p><h1 class="reading-title">${esc(s.title)}${s.subtitle?`<span>${esc(s.subtitle)}</span>`:''}</h1></section>${s.assets.length?`<section class="art-section art-${s.layout||'wide'}"><div class="art-grid">${s.assets.map((a,j)=>`${j===1&&s.description?`<p class="composition-description">${esc(s.description)}</p>`:''}${j>0&&s.arrows?'<div class="art-flow-arrow" role="img" aria-label="从结构拆解到最终效果">↓</div>':''}<figure class="artwork"><a href="${esc(a.src)}" target="_blank" rel="noopener" aria-label="查看大图：${esc(a.label)}"><img src="${esc(a.src)}" width="${a.width}" height="${a.height}" alt="${esc(a.label)}" loading="${j?'lazy':'eager'}"></a><figcaption>${esc(a.label)}<a href="${esc(a.src)}" target="_blank" rel="noopener">查看大图 ↗</a></figcaption></figure>`).join('')}</div></section>`:'<p class="venue-pending">作品资料待补充。</p>'}<nav class="item-pagination" aria-label="项目内容导航"><a href="#/project/${p.slug}">返回目录</a>${i?`<a href="#/project/${p.slug}/${p.pages[i-1].id}">← ${esc(p.pages[i-1].title)}</a>`:''}${next?`<a href="#/project/${p.slug}/${next.id}">${esc(next.title)} →</a>`:''}</nav>`;}

function essayFigure(a){return `<figure class="artwork essay-art"><a href="${esc(a.src)}" target="_blank" rel="noopener" aria-label="查看大图：${esc(a.label)}"><img src="${esc(a.src)}" width="${a.width}" height="${a.height}" alt="${esc(a.label)}" loading="lazy"></a><figcaption>${esc(a.label)}<a href="${esc(a.src)}" target="_blank" rel="noopener">查看大图 ↗</a></figcaption></figure>`;}
function peonyEssay(p){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>PROJECT 03 / 05</span></div><article class="peony-essay"><section class="project-intro"><p class="eyebrow">THE PEONY PAVILION / 牡丹亭</p><h1 class="reading-title">${esc(p.fullTitle)}<span>${esc(p.subtitle)}</span></h1></section><blockquote class="peony-quote"><p>${p.quote.split('  ').map(line=>`<span>${esc(line)}</span>`).join('')}</p><cite>——《牡丹亭》</cite></blockquote>${essayFigure(p.essayAssets[0])}<p class="peony-description">${esc(p.description)}</p>${p.essayAssets.slice(1).map(essayFigure).join('')}</article><nav class="item-pagination" aria-label="作品导航"><a href="#/">返回全部作品</a><a href="#/project/begonia">← 海棠诗梦</a></nav>`;}

function homeHeading(title){const parts=title.split('|');return esc(parts.shift().trim())+(parts.length?'<span class="home-subtitle">| '+esc(parts.join('|').trim())+'</span>':'');}
function jinhuiduiEssay(p){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>PROJECT 04 / 05</span></div><article class="peony-essay jinhuidui-essay"><section class="project-intro"><p class="eyebrow">JINHUIDUI / 锦灰堆</p><h1 class="reading-title">${esc(p.fullTitle)}<span>${esc(p.subtitle)}</span></h1></section><section class="project-facts bag-facts" aria-label="项目信息"><dl>${p.facts.map(([key,values])=>`<div><dt>【${esc(key)}】</dt><dd>${values.map(esc).join('<br>')}</dd></div>`).join('')}</dl></section>${essayFigure(p.essayAssets[0])}<p class="peony-description">${esc(p.description)}</p><section class="decomposition-pending" aria-label="分解图占位"><h2>分解图</h2><p class="muted">待补充</p></section>${p.essayAssets.slice(1).map(essayFigure).join('')}</article><nav class="item-pagination" aria-label="作品导航"><a href="#/">返回全部作品</a><a href="#/project/peony">← 牡丹亭</a></nav>`;}

function salonEssay(p){return `<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>PROJECT 05 / 05</span></div><article class="peony-essay salon-essay"><section class="project-intro"><p class="eyebrow">OPERA SALON / 戏曲妆造沙龙</p><h1 class="reading-title">${esc(p.fullTitle)}<span>${esc(p.subtitle)}</span></h1></section><section class="project-facts salon-facts" aria-label="项目信息"><dl><div><dt>【委托方】</dt><dd>${esc(p.client)}</dd></div><div><dt>【周期】</dt><dd>${esc(p.period)}</dd></div></dl></section>${essayFigure(p.essayAssets[0])}<p class="peony-description">${p.description.split('\n').map(esc).join('<br>')}</p>${essayFigure(p.essayAssets[1])}</article><nav class="item-pagination" aria-label="作品导航"><a href="#/">返回全部作品</a><a href="#/project/project-four">← 白茫茫大地</a></nav>`;}

function wordCloud(){
 const shuffle=items=>{for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}return items;};
 const large=shuffle(['设计','美术','宣传','文化','文创','国风']);
 const small=shuffle(['平面','数媒','全案','建筑','出版','插画','文学','戏曲','活动','跨界','衍生']);
 const largeSlots=new Set([2,6,9,11,13,17]);
 return Array.from({length:17},(_,i)=>{const size=largeSlots.has(i+1)?'large':'small',word=(size==='large'?large:small).pop();return `<span class="cloud-word cloud-${size} word-${i+1}">${word}</span>`;}).join('');
}

function fineArtFigure(a){if(!a.heading)return essayFigure(a);return `<figure class="artwork essay-art"><a href="${esc(a.src)}" target="_blank" rel="noopener"><img src="${esc(a.src)}" width="${a.width}" height="${a.height}" alt="${esc(a.heading)}" loading="lazy"></a><figcaption class="digital-caption"><h2>${a.heading.split('\n').map(esc).join('<br>')}</h2><p>${a.notes.split('\n').map(esc).join('<br>')}</p><a href="${esc(a.src)}" target="_blank" rel="noopener">查看大图 ↗</a></figcaption></figure>`;}

function realizationPage(p){return `<div class="detail-top"><a class="text-link" href="#/project/reading">← 项目目录</a><span>赏读会 / 成品落地</span></div><section class="item-intro"><p class="eyebrow">IN PRACTICE</p><h1>成品落地</h1></section><section class="art-section art-wide"><div class="art-grid">${p.realizationAssets.map(essayFigure).join('')}</div></section><nav class="item-pagination" aria-label="成品落地导航"><a href="#/project/reading">返回项目目录</a><a href="#/project/reading/venue">← 会场视觉</a></nav>`;}
