(() => {
 const dims=[['genre','体裁'],['field','领域'],['theme','主题'],['series','系列'],['region','地域']];
 const key='weiyun-literature-filters';let selected=[];
 try{const saved=JSON.parse(sessionStorage.getItem(key)||'[]');if(Array.isArray(saved))selected=saved.filter(x=>Array.isArray(x)&&dims.some(d=>d[0]===x[0])&&typeof x[1]==='string').map(([d,t])=>[d,d==='field'&&t==='行旅'?'文旅':t]);}catch{}
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const works=()=>window.literatureWorks||[];
 function filtered(){const byDimension=new Map();for(const [d,t] of selected){if(!byDimension.has(d))byDimension.set(d,[]);byDimension.get(d).push(t);}return works().filter(w=>[...byDimension].every(([d,labels])=>labels.some(t=>w[d].includes(t))));}
 function group(items){const years=new Map();for(const w of [...items].sort((a,b)=>a.date.localeCompare(b.date)||a.order-b.order)){if(!years.has(w.year))years.set(w.year,new Map());const months=years.get(w.year);if(!months.has(w.month))months.set(w.month,new Map());const days=months.get(w.month);if(!days.has(w.day))days.set(w.day,[]);days.get(w.day).push(w);}return years;}
 function timeline(items){if(!items.length)return '<p class="literature-empty">没有符合当前筛选条件的作品。可取消部分标签，或清除筛选。</p>';return [...group(items)].map(([year,months])=>'<section class="literature-year"><h2>'+year+'</h2><div class="literature-months">'+[...months].map(([month,days])=>'<section class="literature-month"><h3>'+month+'月</h3><div>'+[...days].map(([day,list])=>'<div class="literature-day"><span class="literature-day-label">'+(day?day+'日':' ')+'</span><ul>'+list.map(w=>'<li><a href="'+esc(w.url)+'">'+esc(w.title)+'<span aria-hidden="true">↗</span></a></li>').join('')+'</ul></div>').join('')+'</div></section>').join('')+'</div></section>').join('');}
 function tags(w){return dims.flatMap(([d,label])=>w[d].map(t=>'<span class="literature-tag" title="'+label+'">'+esc(t)+'</span>')).join('');}
 function index(){return '<div class="detail-top"><a class="text-link" href="#/">← 全部作品</a><span>LITERATURE</span></div><section class="simple-page literature-index"><p class="eyebrow">SELECTED WRITING / 文学作品选</p><h1>文学作品选</h1><div class="literature-filters" aria-label="作品标签筛选">'+dims.map(([d,label])=>'<fieldset><legend>'+label+'</legend><div>'+[...new Set([...(window.literatureTagLibrary?.[d]||[]),...works().flatMap(w=>w[d])])].map(t=>'<button type="button" data-dimension="'+d+'" data-tag="'+esc(t)+'" aria-pressed="'+selected.some(s=>s[0]===d&&s[1]===t)+'">'+esc(t)+'</button>').join('')+'</div></fieldset>').join('')+'<div class="literature-filter-bottom"><p id="literature-count" role="status">'+count()+'</p><button type="button" id="literature-clear">清除筛选</button></div></div><div id="literature-timeline" class="literature-timeline">'+timeline(filtered())+'</div></section>';}
 function count(){return '共 '+filtered().length+' 篇作品'+(selected.length?' · 已选 '+selected.length+' 个标签（同维度满足任一，不同维度同时满足）':'');}
 function bind(){const host=document.querySelector('.literature-filters');if(!host)return;const update=()=>{try{sessionStorage.setItem(key,JSON.stringify(selected))}catch{}host.querySelectorAll('[data-tag]').forEach(b=>b.setAttribute('aria-pressed',selected.some(s=>s[0]===b.dataset.dimension&&s[1]===b.dataset.tag)));document.getElementById('literature-count').textContent=count();document.getElementById('literature-timeline').innerHTML=timeline(filtered());};host.querySelectorAll('[data-tag]').forEach(b=>b.addEventListener('click',()=>{const i=selected.findIndex(s=>s[0]===b.dataset.dimension&&s[1]===b.dataset.tag);if(i<0)selected.push([b.dataset.dimension,b.dataset.tag]);else selected.splice(i,1);update();}));document.getElementById('literature-clear').addEventListener('click',()=>{selected=[];update();});}
 function article(id){const w=works().find(w=>w.id===id);if(!w)return '<section class="simple-page"><h1>未找到作品</h1><a href="#/literature">返回文学作品选</a></section>';return '<div class="detail-top"><a class="text-link" href="#/literature">← 文学作品选</a><span>LITERATURE</span></div><article class="literature-article"><header class="literature-article-heading"><p class="eyebrow">'+esc(w.dateLabel)+'</p><h1>'+esc(w.title)+'</h1><div class="literature-tags">'+tags(w)+'</div></header><div class="literature-body" id="literature-body" aria-busy="true"><p>正文加载中…</p></div><div class="literature-article-bottom"><a class="text-link" href="#/literature">← 返回文学作品选</a></div></article>';}
 function load(id){const host=document.getElementById('literature-body');const w=works().find(w=>w.id===id);if(!host||!w)return;const apply=()=>{if(location.hash!=='#/literature/'+id)return;host.innerHTML=window.literatureBodies[id];host.setAttribute('aria-busy','false');};window.literatureBodies=window.literatureBodies||{};if(window.literatureBodies[id]){apply();return;}const script=document.createElement('script');script.src='./literature/pages/'+id+'.js';script.onload=()=>{apply();script.remove()};script.onerror=()=>{host.innerHTML='<p>正文未能加载，请刷新页面重试。</p>';host.setAttribute('aria-busy','false');script.remove()};document.head.append(script);}
 document.addEventListener('click',event=>{const a=event.target.closest?.('[data-lit-target]');if(!a)return;event.preventDefault();const target=document.getElementById(a.dataset.litTarget);if(target){target.scrollIntoView({behavior:'smooth',block:'center'});target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}});
 window.Literature={index,article,bind,load,filtered,group};
})();
